GET http://localhost:8080/api/v1/professores

### Buscar todos os professores
GET http://localhost:8080/api/v1/professores

### Buscar professor pelo ID
GET http://localhost:8080/api/v1/professores/1
### Inserir um novo Professor
POST http://localhost:8080/api/v1/professores
Content-Type: application/json

{
  "id": "3",
  "nome": "Robert",
  "curso": "Engenharia Robotica",
  "sexo": "Masculino",
  "cpf": "400.289.224-20",
  "cursoId": "140",
  "telefone": "40028922",
  "idade": "40"

}

### Atualizar o  Professor
PUT http://localhost:8080/api/v1/professores/93c661e2-9107-48f5-909f-175c2f93055e
Content-Type: application/json

{
  "id": "5",
  "nome": "Richarlison",
  "curso": "Engenharia Mecanica",
  "sexo": "Masculino",
  "cpf": "130.120.920-40",
  "cursoId": "135",
  "telefone": "34342305",
  "idade": "20"
}

### Remover o Professor
DELETE  http://localhost:8080/api/v1/professores/5
Content-Type: application/json