GET http://localhost:8080/api/v1/professores

### Buscar todos os professores
GET http://localhost:8080/api/v1/professores

### Buscar professor pelo ID
GET http://localhost:8080/api/v1/professores/870282f0-bcd3-48b1-9293-a5c5488f7b10

### Inserir um novo Professor
POST http://localhost:8080/api/v1/professores
Content-Type: application/json

{
  "id": "3",
  "nome": "Felix",
  "curso": "Engenharia Robotica",
  "turma": "Primeiro Semestre"
}

### Atualizar o  Professor
PUT http://localhost:8080/api/v1/professores/870282f0-bcd3-48b1-9293-a5c5488f7b10
Content-Type: application/json

{
  "id": "3",
  "nome": "Leandro",
  "curso": "Medicina",
  "turma": "Segundo Semestre"
}

### Remover o Professor
DELETE  http://localhost:8080/api/v1/professores/870282f0-bcd3-48b1-9293-a5c5488f7b10
Content-Type: application/json